name: Convert resources[bot]
on:
 pull_request:
    branches: [main]
 push:
    branches: [main]
    paths: 
      - '.github/workflows/main.yml'
      - 'c.sh'
 schedule:
   - cron: '0 * * * *'
 repository_dispatch:
   types: [update_resources]
jobs:
  convert_resources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install jq
        shell: bash
        run: |
          sudo apt install jq
          jq --version
      - name: Convert resources 1.18 -> 1.19.3
        id: convert_resources
        shell: bash
        run: |
          # 转换
          echo '======================= 环境变量设置 ========================='
          # 下载链接前缀，后面不得加 /
          export "dLINK=https://ghproxy.com/https://raw.githubusercontent.com/zkitefly/TranslationPackMirror/main/files$dLINK"
          # 下载文件的名字，带 .zip
          export "dNAME=Minecraft-Mod-Language-Modpack-1-18.zip$dNAME"
          # 转换的名字，带 .zip
          export "cNAME=Minecraft-Mod-Language-Modpack-1-18T1-19-3.zip$cNAME"
          # 修改资源包 pack_format 的 value
          export "cV=12$cV"
          # 校验文件名字，带 .md5
          export "mNAME=1.18T1.19.3.md5$mNAME"
          # commit 标题名称，Convert resources + XXX
          export "CM=1.18 to 1.19.3$CM"
          echo '======================= 运行修改脚本 ========================='
          echo "========================== 预览 ============================="
          echo "./c.sh"
          echo "============================================================"
          ./c.sh
          echo '============================================================'
          # 清除环境变量，以防沾染其他工作流，若环境变量设置添加了新的设置，请在 clean.sh 中一并添加
          ./clean.sh
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff-index --quiet HEAD; then
            # No changes
            echo 'changed=false' >> $GITHUB_OUTPUT
          else
            # Changes detected
            echo 'changed=true' >> $GITHUB_OUTPUT
            git commit -m "Convert resources $CM

          GitHub Action: https://github.com/${{ github.repository }}/actions/runs/$GITHUB_RUN_ID
            "
          fi
      - name: Convert resources 1.18 -> 1.19.1/2
        id: convert_resources1
        shell: bash
        run: |
          # 转换
          echo '======================= 环境变量设置 ========================='
          # 下载链接前缀，后面不得加 /
          export "dLINK=https://ghproxy.com/https://raw.githubusercontent.com/zkitefly/TranslationPackMirror/main/files$dLINK"
          # 下载文件的名字，带 .zip
          export "dNAME=Minecraft-Mod-Language-Modpack-1-18.zip$dNAME"
          # 转换的名字，带 .zip
          export "cNAME=Minecraft-Mod-Language-Modpack-1-18T1-19-1o2.zip$cNAME"
          # 修改资源包 pack_format 的 value
          export "cV=9$cV"
          # 校验文件名字，带 .md5
          export "mNAME=1.18T1.19.1o2.md5$mNAME"
          # commit 标题名称，Convert resources + XXX
          export "CM=1.18 to 1.19.1/2$CM"
          echo '======================= 运行修改脚本 ========================='
          echo "========================== 预览 ============================="
          echo "./c.sh"
          echo "============================================================"
          ./c.sh
          echo '============================================================'
          # 清除环境变量，以防沾染其他工作流，若环境变量设置添加了新的设置，请在 clean.sh 中一并添加
          ./clean.sh
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff-index --quiet HEAD; then
            # No changes
            echo 'changed=false' >> $GITHUB_OUTPUT
          else
            # Changes detected
            echo 'changed=true' >> $GITHUB_OUTPUT
            git commit -m "Convert resources $CM

          GitHub Action: https://github.com/${{ github.repository }}/actions/runs/$GITHUB_RUN_ID
            "
          fi
      - name: Convert resources 1.16 -> 1.17
        id: convert_resources2
        shell: bash
        run: |
          # 转换
          echo '======================= 环境变量设置 ========================='
          # 下载链接前缀，后面不得加 /
          export "dLINK=https://ghproxy.com/https://raw.githubusercontent.com/zkitefly/TranslationPackMirror/main/files$dLINK"
          # 下载文件的名字，带 .zip
          export "dNAME=Minecraft-Mod-Language-Modpack-1-16.zip$dNAME"
          # 转换的名字，带 .zip
          export "cNAME=Minecraft-Mod-Language-Modpack-1-16T1-17.zip$cNAME"
          # 修改资源包 pack_format 的 value
          export "cV=7$cV"
          # 校验文件名字，带 .md5
          export "mNAME=1.16T1.17.md5$mNAME"
          # commit 标题名称，Convert resources + XXX
          export "CM=1.16 -> 1.17$CM"
          echo '======================= 运行修改脚本 ========================='
          echo "========================== 预览 ============================="
          echo "c.sh"
          echo "============================================================"
          ./c.sh
          echo '============================================================'
          # 清除环境变量，以防沾染其他工作流，若环境变量设置添加了新的设置，请在 clean.sh 中一并添加
          ./clean.sh
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff-index --quiet HEAD; then
            # No changes
            echo 'changed=false' >> $GITHUB_OUTPUT
          else
            # Changes detected
            echo 'changed=true' >> $GITHUB_OUTPUT
            git commit -m "Convert resources $CM

          GitHub Action: https://github.com/${{ github.repository }}/actions/runs/$GITHUB_RUN_ID
            "
          fi
      - name: Convert resources 1.18-Fabric -> 1.19.3-Fabric
        id: convert_resources3
        shell: bash
        run: |
          # 转换
          echo '======================= 环境变量设置 ========================='
          # 下载链接前缀，后面不得加 /
          export "dLINK=https://ghproxy.com/https://raw.githubusercontent.com/zkitefly/TranslationPackMirror/main/files$dLINK"
          # 下载文件的名字，带 .zip
          export "dNAME=Minecraft-Mod-Language-Modpack-1-18-Fabric.zip$dNAME"
          # 转换的名字，带 .zip
          export "cNAME=Minecraft-Mod-Language-Modpack-1-18-FabricT1-19-3-Fabric.zip$cNAME"
          # 修改资源包 pack_format 的 value
          export "cV=12$cV"
          # 校验文件名字，带 .md5
          export "mNAME=1.18-FabricT1.19.3-Fabric.md5$mNAME"
          # commit 标题名称，Convert resources + XXX
          export "CM=1.18-Fabric to 1.19.3-Fabric$CM"
          echo '======================= 运行修改脚本 ========================='
          echo "========================== 预览 ============================="
          echo "./c.sh"
          echo "============================================================"
          ./c.sh
          echo '============================================================'
          # 清除环境变量，以防沾染其他工作流，若环境变量设置添加了新的设置，请在 clean.sh 中一并添加
          ./clean.sh
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff-index --quiet HEAD; then
            # No changes
            echo 'changed=false' >> $GITHUB_OUTPUT
          else
            # Changes detected
            echo 'changed=true' >> $GITHUB_OUTPUT
            git commit -m "Convert resources $CM

          GitHub Action: https://github.com/${{ github.repository }}/actions/runs/$GITHUB_RUN_ID
            "
          fi
      - name: Convert resources 1.18-Fabric -> 1.19.1/2-Fabric
        id: convert_resources4
        shell: bash
        run: |
          # 转换
          echo '======================= 环境变量设置 ========================='
          # 下载链接前缀，后面不得加 /
          export "dLINK=https://ghproxy.com/https://raw.githubusercontent.com/zkitefly/TranslationPackMirror/main/files$dLINK"
          # 下载文件的名字，带 .zip
          export "dNAME=Minecraft-Mod-Language-Modpack-1-18-Fabric.zip$dNAME"
          # 转换的名字，带 .zip
          export "cNAME=Minecraft-Mod-Language-Modpack-1-18-FabricT1-19-1o2-Fabric.zip$cNAME"
          # 修改资源包 pack_format 的 value
          export "cV=9$cV"
          # 校验文件名字，带 .md5
          export "mNAME=1.18-FabricT1.19.1o2-Fabric.md5$mNAME"
          # commit 标题名称，Convert resources + XXX
          export "CM=1.18-Fabric to 1.19.1/2-Fabric$CM"
          echo '======================= 运行修改脚本 ========================='
          echo "========================== 预览 ============================="
          echo "./c.sh"
          echo "============================================================"
          ./c.sh
          echo '============================================================'
          # 清除环境变量，以防沾染其他工作流，若环境变量设置添加了新的设置，请在 clean.sh 中一并添加
          ./clean.sh
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff-index --quiet HEAD; then
            # No changes
            echo 'changed=false' >> $GITHUB_OUTPUT
          else
            # Changes detected
            echo 'changed=true' >> $GITHUB_OUTPUT
            git commit -m "Convert resources $CM

          GitHub Action: https://github.com/${{ github.repository }}/actions/runs/$GITHUB_RUN_ID
            "
          fi
      - name: Convert resources 1.16-Fabric -> 1.17-Fabric
        id: convert_resources5
        shell: bash
        run: |
          # 转换
          echo '======================= 环境变量设置 ========================='
          # 下载链接前缀，后面不得加 /
          export "dLINK=https://ghproxy.com/https://raw.githubusercontent.com/zkitefly/TranslationPackMirror/main/files$dLINK"
          # 下载文件的名字，带 .zip
          export "dNAME=Minecraft-Mod-Language-Modpack-1-16-Fabric.zip$dNAME"
          # 转换的名字，带 .zip
          export "cNAME=Minecraft-Mod-Language-Modpack-1-16-FabricT1-17-Fabric.zip$cNAME"
          # 修改资源包 pack_format 的 value
          export "cV=7$cV"
          # 校验文件名字，带 .md5
          export "mNAME=1.16-FabricT1.17-Fabric.md5$mNAME"
          # commit 标题名称，Convert resources + XXX
          export "CM=1.16-Fabric -> 1.17-Fabric$CM"
          echo '======================= 运行修改脚本 ========================='
          echo "========================== 预览 ============================="
          echo "./c.sh"
          echo "============================================================"
          ./c.sh
          echo '============================================================'
          # 清除环境变量，以防沾染其他工作流，若环境变量设置添加了新的设置，请在 clean.sh 中一并添加
          ./clean.sh
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff-index --quiet HEAD; then
            # No changes
            echo 'changed=false' >> $GITHUB_OUTPUT
          else
            # Changes detected
            echo 'changed=true' >> $GITHUB_OUTPUT
            git commit -m "Convert resources $CM

          GitHub Action: https://github.com/${{ github.repository }}/actions/runs/$GITHUB_RUN_ID
            "
          fi
      - name: Push changes
        # 注意：在新增一个转换时，一定要在下方的 if 规则，否则当该资源包更新时无法检测到它！
        if: steps.convert_resources.outputs.changed == 'true' || steps.convert_resources1.outputs.changed == 'true' || steps.convert_resources2.outputs.changed == 'true' || steps.convert_resources3.outputs.changed == 'true' || steps.convert_resources4.outputs.changed == 'true' || steps.convert_resources5.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
#模板：
#      - name: Convert resources  -> 
#        id: convert_resources
#        shell: bash
#        run: |
#          # 转换
#          echo '======================= 环境变量设置 ========================='
#          # 下载链接前缀，后面不得加 /
#          export "dLINK=https://ghproxy.com/https://raw.githubusercontent.com/zkitefly/TranslationPackMirror/main/files$dLINK"
#          # 下载文件的名字，带 .zip
#          export "dNAME=Minecraft-Mod-Language-Modpack- .zip$dNAME"
#          # 转换的名字，带 .zip
#          export "cNAME=Minecraft-Mod-Language-Modpack- T .zip$cNAME"
#          # 修改资源包 pack_format 的 value
#          export "cV= $cV"
#          # 校验文件名字，带 .md5
#          export "mNAME= T .md5$mNAME"
#          # commit 标题名称，Convert resources + XXX
#          export "CM=  to  $CM"
#          echo '======================= 运行修改脚本 ========================='
#          echo "========================== 预览 ============================="
#          echo "./c.sh"
#          echo "============================================================"
#          ./c.sh
#          echo '============================================================'
#          # 清除环境变量，以防沾染其他工作流，若环境变量设置添加了新的设置，请在 clean.sh 中一并添加
#          ./clean.sh
#          git config --local user.name "github-actions[bot]"
#          git config --local user.email "github-actions[bot]@users.noreply.github.com"
#          git add -A
#          if git diff-index --quiet HEAD; then
#            # No changes
#            echo 'changed=false' >> $GITHUB_OUTPUT
#          else
#            # Changes detected
#            echo 'changed=true' >> $GITHUB_OUTPUT
#            git commit -m "Convert resources $CM
#
#          GitHub Action: https://github.com/${{ github.repository }}/actions/runs/$GITHUB_RUN_ID
#            "
#          fi
